## our React TodoMVC app is written
## in node so thats what we select.
## Cypress is agnostic to your apps
## backend language though.
language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci

before_script:
  - npm start -- --silent &

script:
  - npm run cypress:run
notifications:
  slack: traviscinotif-ick8871:shFRbchUKAQElpbWpJ7XtEtA